### ISSUE TITLE
Internal mic doesnt work

### ISSUE THREAD

**Issue by bayungr** [GrieferPig/acer-sfx14-41g-hackintosh#1]
I installed on Sonoma 14.1. Everything is fine except the internal mic. It detect the internal mic but there is no sound registered

**Comment by GrieferPig** [comment]
Sonoma is not tested w/ this EFI, but it's probably a driver issue. Try upgrade AppleALC.

**Comment by GrieferPig** [comment]
Sonoma is not tested, but it's probably a driver issue.
Try upgrade AppleALC

**Comment by bayungr** [comment]
What version did you use in this configuration?

**Comment by GrieferPig** [comment]
I tested it with Ventura, 13.4.1
